config/routes.rb
Rails.application.routes.draw do
  get 'main' =>'posts#index'

  post 'posts' => 'posts#create'
  get 'posts/new' => 'posts#new', as: 'new_post'

  root 'posts#index'
  
  resources 'posts'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
    def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts=Post.all
    @posts = Post.search(params[:search])
  end

  def new
    @post=Post.new
    @posts=Post.all
  end
  
  def create
    post = Post.new(post_params)
    post.save
    #redirect_to :main
    redirect_to :back
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <style> 
  .nav {
    list-style-type: none;
    background-color: #BDBDBD;
    margin: 0;
    padding: 0;
    float: left;
    border-radius: 10px;
    padding: 15px 10px;
  }

#home{
   font-weight: bold;
   font-size: 17px;
   font-family: Helvetica, sans-serif;
   text-align: center;
   border-radius: 10px;
   background-color: #999999;
   padding: 7px 10px;
}

#new{
   font-weight: bold;
   font-size: 18px;
   font-family: Helvetica, sans-serif;
   text-align: center;
   border-radius: 10px;
   background-color: #999999;
   padding: 5px 10px;
}
  </style>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="nav">
   <div id="home">
   <li><%= link_to 'HOME', main_path %></li>
   </div>
   <br>
   <div id="new">
   <li><%= link_to 'NEW', new_post_path %></li>
   </div>
  </ul>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
 <style>
  body{
    background-color: #669966;
    font-size: 20px;
    margin: 20px 40px 20px 40px;
}


.topic{
    background-color: #CCCCCC;
    font-family: Arial, sans-serif;
    line-height: 0px;
    font-size: 80px;
    font-weight: bold;
    color: #675959;
    text-align: center;
    margin: 40px 120px 40px 120px;
    padding: 20px 20px 5px 20px;
    border-radius: 30px;
}

#inner{
    border-radius: 30px;
    background-color: #bfc4bb;
    line-height: 40px;
    margin: 20px 0px;
    font-weight: bold;
    font-size: 23px;
    padding: 10px 40px;
    color: #444343;
}

#outer{
    background-color: #CCCCCC;
    border-radius: 30px;
    padding: 50px 330px;
    float : middle;
    width: 550px;
    margin: 0 auto;
    text-align: center;
}

#info
{
    text-align: center;
    font-family: Arial, sans-serif;
    font-size: 20px;
    font-weight: bold;
    color: #CFCFCF;
    padding: 30px;
}

textarea#postbody{
    resize: none;
}
</style>
  <title>대나무숲 모든글보기</title>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="posts.css">
</head>

<body>
    <br>
    <hr>
search
<%= form_tag posts_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

    <div class="topic">
        <img src="http://wp.production.patheos.com/blogs/pagantama/files/2016/05/tanabata.png" height="150">
        <p>LIKELION X Bamboo Grove</p>
    </div>

  <div id="outer">
    <% @posts.each_with_index do |p, index| %>
  <div id="inner">
    <br>
    <%= index+1 %>번째 울림<br><br>
    NAME : <%= p.title %><br>
    <%= p.body %> <br><br>
  </div>
  <br>
<% end %>
</div>
</div>
  <div id="info">
    <p>ⓒ 2017. Yeonwoo Cho all rights reserved.</p>
    <p>CONTACT  :  010.4695.1712</p>
  </div>
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
 <style>
  body{
    background-color: #669966;
    font-size: 20px;
    margin: 20px 40px 20px 40px;
}

.topic{
    background-color: #CCCCCC;
    font-family: Arial, sans-serif;
    line-height: 0px;
    font-size: 80px;
    font-weight: bold;
    color: #675959;
    text-align: center;
    margin: 40px 120px 40px 120px;
    padding: 20px 20px 5px 20px;
    border-radius: 30px;
}

.form{
    border-radius: 30px;
    background-color: #CCCCCC;
    width: 150px;
    margin: 0 20px 30px 500px;
    padding: 0px 150px;
    text-align: center;
    font-weight: bold;
    font-size: 25px;
    color: #444343;
}
    

#inner{
    border-radius: 30px;
    background-color: #bfc4bb;
    line-height: 40px;
    margin: 20px 0px;
    font-weight: bold;
    font-size: 23px;
    padding: 10px 40px;
    color: #444343;
}

#outer{
    background-color: #CCCCCC;
    border-radius: 30px;
    padding: 50px 330px;
    width: 550px;
    margin: 0 auto;
    text-align: center;
}

#info
{
    text-align: center;
    font-family: Arial, sans-serif;
    font-size: 20px;
    font-weight: bold;
    color: #CFCFCF;
    padding: 30px;
    float: center;
}

textarea#postbody{
    resize: none;
}
</style>
  <title>대나무숲 새글쓰기</title>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="posts.css">
</head>

<body>
     <div class="topic">
        <img src="http://wp.production.patheos.com/blogs/pagantama/files/2016/05/tanabata.png" height="150">
        <p>LIKELION X Bamboo Grove</p>
    </div>
        <div class="form">
         <%= form_for @post do |f|%>
         <br><br>USER'S NAME
         <%= f.text_field :title, size: 8 %>
        <br><br>
         CONTENT
         <%= f.text_area :body, rows: 5 %><br><br>
         <%= f.submit 'submit' %><br><br>
         <% end %>
        <br>
        </div>
        
     <div id="outer">
     <% @posts.each_with_index do |p, index| %>
       <div id="inner">
       <br>
       <%= index+1 %>번째 울림<br><br>
       <%= p.title %><br>
       <%= p.body %> <br><br>  
       </div>
       <br>
      <% end %>
     </div>
     
  <div id="info">
    <p>ⓒ 2017. Yeonwoo Cho all rights reserved.</p>
    <p>CONTACT  :  010.4695.1712</p>
  </div>
</body>
</html>


<!--<div>-->
<!--    <% @posts.each do |p| %>-->
<!--    <%= p.body %> <br>-->
<!--    <% end %>-->
<!--<div>-->